Repository FDU-SW20-6A/Frontend, pull requests merged in 2020-05, with the labels that each got.

#50 调整layout和周报页面代码
  config/config.js
  config/themePluginConfig.js
  package.json
  src/assets/logo.png
  src/components/Charts/weekly/conNum.js
  src/components/Charts/weekly/conadd.js
  src/components/Charts/weekly/cureNum.js
  src/components/Charts/weekly/deathNum.js
  src/components/WorldList/index.jsx
  src/global.less
  src/layouts/BasicLayout.jsx
  src/pages/CountryDetails.jsx
  src/pages/ProvinceDetails.jsx
  src/pages/Weekly.jsx
  src/pages/Welcome.jsx
  src/pages/World.jsx
Labels: bug, 前端, 前端开发

#58 感染日历功能
  src/components/Charts/PieSeries.jsx
  src/components/Charts/ProvincesConfirm.js
  src/components/Charts/chart_3.jsx
  src/pages/Welcome.jsx
Labels: 前端, 前端开发

#65 puppeteer e2e test
  src/e2e/World.e2e.js
Labels: Test, 前端

#68 首页、世界疫情页面超链接有效性测试；World list搜索功能端到端黑盒测试
  report.20200528.154414.6612.0.001.json
  src/components/Charts/PieSeries.jsx
  src/e2e/Welcome.e2e.js
  src/e2e/World.e2e.js
Labels: Test, 前端
